# -*- coding: utf-8 -*-

# SPDX-FileCopyrightText: 2016-2019 The Atlite Authors
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: atlite-doc
channels:
  - conda-forge
dependencies:
  - python>=3.6

  # Recommended for pandas and xarray
  - bottleneck
  - numexpr
  - pandas>=0.22.0
  - xarray>=0.11.2
  - dask>=0.18.0
  - progressbar2
  - numpy
  - scipy
  - cdsapi
  - pyyaml

  # GIS dependencies have to come all from conda-forge

  - conda-forge::pyproj
  - conda-forge::rasterio
  - conda-forge::shapely
  - conda-forge::geopandas
  - conda-forge::rtree
  # - conda-forge::nbsphinx

  - pip
  - pip:
    - . 
  # Installed by Readthedocs 
  # - sphinx
  # - sphinx_rtd_theme
  # - numpydoc
  # - nbsphinx
