# -------------------*DEFAULT SETTINGS*------------------- #
# --------------------*DO NOT CHANGE*--------------------- #
# For custom settings, see the 'config.example.yaml' file. #
# --------------------*DO NOT CHANGE*--------------------- #

# Folder for storing prepared cutout files
cutout_dir: <ATLITE>/cutouts

# Folder containing raw dataset data
gebco_path: <ATLITE>/data/gebco
ncep_dir:   <ATLITE>/data/ncep
cordex_dir: <ATLITE>/data/cordex
sarah_dir:  <ATLITE>/data/sarah

# Folder for different wind turbine configuration files
windturbine_dir: <ATLITE>/resources/windturbine

# Folder for different solar panel configuration files
solarpanel_dir: <ATLITE>/resources/solarpanel