# -------------------*DEFAULT SETTINGS*------------------- #
# --------------------*DO NOT CHANGE*--------------------- #
# For custom settings, see the 'config.example.yaml' file. #
# --------------------*DO NOT CHANGE*--------------------- #

# Folder for storing prepared cutout files
cutout_dir: <ATLITE>/cutouts

# Folder containing raw dataset data
gebco_path: None
ncep_dir:   None
cordex_dir: None
sarah_dir:  None

# Folder for different wind turbine configuration files
windturbine_dir: <ATLITE>/resources/windturbine

# Folder for different solar panel configuration files
solarpanel_dir: <ATLITE>/resources/solarpanel